sudo: required
dist: trusty
services:
  - docker
install:
  - docker build -t codestyle .
script:
  - docker run --rm --volume=`pwd`:/code 
        --workdir=/code
        --entrypoint=/usr/bin/python
        codestyle runtests.py
  - docker run --rm --volume=`pwd`:/code
      --workdir=/code
      codestyle
      ./codestyle
      ./*.py
      ./tests/*.py
  - docker run --rm --volume=`pwd`:/code
      --workdir=/code
      codestyle --language py
      ./scripts/codestyle
