language: python
python:
  - "2.7"
  - "pypy"
# command to install dependencies
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y python-pip npm php-pear libxml2-dev
  - sudo apt-get install -y build-essential python-dev libjpeg-dev libpng-dev
  - sudo npm install -g jshint jscs-fixer csscomb htmlcs walk brace-expansion
  - sudo pear install PHP_CodeSniffer
install:
  - pip install -r requirements.txt
# command to run tests
script: python runtests.py
