sudo: required
dist: trusty
services:
  - docker
install:
  - docker build -t codestyle .
script:
  - docker run --volume=`pwd`:/code 
        --workdir=/code
        --entrypoint=/usr/bin/python
        webpp/codestyle runtests.py
