sudo: required
dist: trusty
language: python
services:
  - docker
install:
  - sudo add-apt-repository ppa:fkrull/deadsnakes -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-tox python3 python3.5 python3-pip nodejs npm php-pear python-setuptools python3-setuptools
#  - ./ci/build.sh
#before_install:
#  - sudo apt-get update -qq
#  - sudo apt-get install -qq python-tox python3 python3.5* python3-pip nodejs npm php-pear python-setuptools python3-setuptools
script:
  - tox
